language: cpp
compiler:
  - gcc
  - clang
cache: apt
before_install:
 - sudo add-apt-repository --yes ppa:kalakris/cmake
 - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake g++-4.8 valgrind
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
before_script: mkdir build && cd build
script: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_ESCRIPT_APPLICATION=ON -DBUILD_ESCRIPT_TEST=ON .. && make && cpack && cp libEScript.tar.gz /tmp && cd /tmp && tar xzf libEScript.tar.gz && cd libEScript/share/EScript && LD_LIBRARY_PATH=../../lib/x86_64-linux-gnu/ ../../bin/escript_test && LD_LIBRARY_PATH=../../lib/x86_64-linux-gnu/ valgrind --tool=memcheck --leak-check=no --track-origins=yes --error-exitcode=200 ../../bin/escript_test

